/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   paper-input.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../shadycss/apply-shim.d.ts" />
/// <reference path="../polymer/types/lib/elements/custom-style.d.ts" />
/// <reference path="../iron-input/iron-input.d.ts" />
/// <reference path="paper-input-container.d.ts" />
/// <reference path="paper-input-behavior.d.ts" />
/// <reference path="paper-input-error.d.ts" />

declare namespace AnypointElements {

  /**
   * `<paper-input>` single line text input styled for the Anypoint platform as a Polymer
   * powered web component
   *
   * It may include an optional error message.
   *
   * ```html
   * <paper-input required error-message="Value is required"></paper-input>
   * ```
   *
   * It may include a custom validator(s).
   *
   * ```html
   * <paper-input validator="my-validator" error-message="Value is required"></paper-input>
   * ```
   *
   * See `Anypoint.AnypointValidatableBehavior` for API and examples.
   *
   * ### Styling
   *
   * See `anypoint-text-container` for styling options.
   */
  class PaperInput extends
    Polymer.PaperInputBehavior(
    Polymer.Element) {

    /**
     * Returns a reference to the focusable element. Overridden from PaperInputBehavior
     * to correctly focus the native input.
     */
    readonly _focusableElement: HTMLElement;
    connectedCallback(): void;
    disconnectedCallback(): void;
    _onIronInputReady(): void;
  }
}

interface HTMLElementTagNameMap {
  "paper-input": AnypointElements.PaperInput;
}
